services:
  - type: web
    name: grammar-error-correction
    env: python
    buildCommand: pip install -r requirements_render.txt
    startCommand: python app_render.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 10000 